### ISSUE TITLE
Wrong Alert, CIVA-Glider Advanced Known Free

### ISSUE THREAD

**Issue by AcroDirki** [OpenAero/main#204]
Hi guys,

we recognized a wrong alert, when designing the known free sequence acc. to CIVA-Glider Rules in Advanced Category:
The sequence is designed to finish in positive attitude, but the error message occur, that "sequence must finish upright!". In Ulimited Category, the wrong error does not occur.
Thanks for your great work!

D.

**Comment by OpenAero** [comment]
This does not seem to occur with all sequences. Please post the relevant
sequence string where this does occur.

**Comment by AcroDirki** [comment]
A friend, which uses the app, downloaded via firefox and manually installed, noted this error message for the following sequence string. Now, I'm able to reproduce the error in the chrome-app.

2a2- "@A" -1% -d2 2a22++~ (8,5) "@B" ``h`+~ ita```4+``` p4 "@D" -1% `q(1)``+` "@C" -2% 2rdb..' (-4,0) "@E" .m2+~ (2,11) -2% id.

Meanwhile, I investigated that the error just occurs, after the last dot in the entire string is entered. If this dot is missing, the wrong alert disappears.

Best regards and thanks for your efforts,
D.

**Comment by OpenAero** [comment]
Fixed in 2016.3

**Comment by AcroDirki** [comment]
Obviously, this error is still present in glider UNL category. Last figure was 1j1^
Propose to check for all different rules/categories.
